plugins {
    alias(libs.plugins.android.library)
    id "jacoco"
}

android {
    namespace = "br.com.tresvtintas.mobile.feature.catalogadmin"
    compileSdk = libs.versions.compileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildTools.get()

    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    lint {
        abortOnError = true
        checkReleaseBuilds = true
        warningsAsErrors = true
        htmlReport = true
        xmlReport = true
        sarifReport = true
    }
}

dependencies {
    api(project(":core:catalogadmin"))
    implementation(project(":core:designsystem"))
    implementation(libs.androidx.activity)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.core)
    implementation(libs.androidx.recyclerview)
    implementation(libs.material)
    testImplementation(libs.junit4)
}

apply from: rootProject.file("gradle/quality.gradle")

jacoco {
    toolVersion = libs.versions.jacoco.get()
}

tasks.withType(Test).configureEach {
    useJUnit()
}
