package br.com.tresvtintas.mobile.core.network.problem;

public enum MobileProblemCode {
    AUTH_REQUIRED,
    AUTH_FAILED,
    APP_UPDATE_REQUIRED,
    FORBIDDEN,
    IDEMPOTENCY_IN_PROGRESS,
    IDEMPOTENCY_KEY_REUSED,
    INTERNAL_ERROR,
    INVALID_JSON,
    INVALID_REQUEST,
    METHOD_NOT_ALLOWED,
    NOT_FOUND,
    PAYLOAD_TOO_LARGE,
    PRICE_LIST_SELECTION_REQUIRED,
    PRICE_NOT_AVAILABLE,
    PRICE_POLICY_CHANGED,
    PRICE_LIST_NOT_PUBLISHED,
    TINT_MAPPING_PENDING,
    REVISION_CONFLICT,
    PRICING_ENGINE_DISABLED,
    RATE_LIMITED,
    RESOURCE_CONFLICT,
    SERVICE_UNAVAILABLE
}
