package br.com.tresvtintas.mobile.core.quote;

public enum MaterialQuoteFailureKind {
    ACCESS_REVOKED,
    AUTH_REJECTED,
    CONFLICT,
    FORBIDDEN,
    IDEMPOTENCY_IN_PROGRESS,
    IDEMPOTENCY_KEY_REUSED,
    INVALID_REQUEST,
    LOCAL_STORAGE,
    NETWORK,
    NOT_FOUND,
    PRICE_LIST_NOT_PUBLISHED,
    PRICE_LIST_SELECTION_REQUIRED,
    PRICE_NOT_AVAILABLE,
    PRICE_POLICY_CHANGED,
    PRICING_ENGINE_DISABLED,
    PROTOCOL,
    RATE_LIMITED,
    SERVICE_UNAVAILABLE,
    TINT_MAPPING_PENDING,
    UPDATE_REQUIRED
}
